### ISSUE TITLE
How can I use it? 

### ISSUE THREAD

**Issue by bagobor** [starwing/lua-nanovg#1]
Sorry for lame question (I'm new to lua modules).
But can you be so kind to add step-by-step tutorial for your module? 
Big thanks anyway!

**Comment by bagobor** [comment]
I suppose LUA's 'require' automatically calls "luaopen_%module_name%" for native modules? Am I right?

**Comment by starwing** [comment]
Hi, thanks for notice this module :)

 So, what kind of tutorial you want? basicly, after you install this module, you can run test.lua to see it works properly. and look into this file to know how to use it.

it just a thin wrapper for nanovg library, so documents of nanovg can used, you can go to [NanoVG][https://github.com/memononen/nanovg] to see details.

for install it, you can build nanovg and nvg.dll (for windows) or nvg.so (for *nix) yourself, but the easier way is using luarocks:

```
luarocks install glfw
luarocks install nanovg
```

after that, you can run test.lua directly, and try other functions yourself. :)

btw, the module name is after `luaopen_`, and replace `_` with `.`, e.g. luaopen_pb_buffer can be in pb.dll and use require "pb.buffer" to include it.

**Comment by bagobor** [comment]
Thanks for clearing this out! (Module wasnt published at luarocks 7 days ago :) )
