### ISSUE TITLE
luarocks does not work on OSX

### ISSUE THREAD

**Issue by iongion** [starwing/lua-nanovg#5]
I have no clue why this happens, both new to lua and nanovg:

```
luarocks install nanovg --local
Installing https://luarocks.org/nanovg-0.1.1-1.src.rock

Error: Failed extracting 0.1.1.tar.gz
```

**Comment by starwing** [comment]
I found it, I fixed it on my Mac, maybe you should make it in repo using luarocks make? I haven't make a new release yet

**Comment by iongion** [comment]
Thank you for solving it!
