### ISSUE TITLE
Update test.lua to include some image examples

### ISSUE THREAD

**Issue by iongion** [starwing/lua-nanovg#6]
For those both new to lua and nanovg, this would be really helpful.
How do you load(from file) and draw an image  ?
I have tried
```im = ctx.image.load(file)```
to no avail

**Comment by iongion** [comment]
I like your library a lot, I am even trying to create my own bindings to nanovg and nanosvg to be able to learn both lua and opengl, but it is amateurish and does not do anything useful https://github.com/iongion/lunavg I am stuck at exposing stuff to Lua, you guys seem to have a very advanced Lua C api understanding.

This project is very nice https://github.com/stetre/moonlibs , you could try to follow his path of documentation and file organization, even join hands(as he has a gl and glfw implementation, you wouldn't need to bind to those ? 👍 He is very helpful and responsive, even responding to mere mortals such as me.

Anyway, you have an awesome project that I would like to integrate somehow in ZeroBrane to do live opengl coding! Many thanks and hoping for the docs improvement!

**Comment by starwing** [comment]
Thanks for informations of a great glfw binding!

the NanoVG binding can use separate with OpenGL binding. I will look info the MoonLibs project to see how I could help, thanks for feedback :)

**Comment by iongion** [comment]
Awesome! Thank you!

**Comment by iongion** [comment]
I am here with the images toying around:

```
local function loadData(ctx)
  im = ctx:image("nanovg/example/images/image1.png", "flipy")
  return {
    context = ctx,
    im = im,
  }
end

loaded = loadData(ctx)

local function drawImages(ctx, width, height)
  ctx.strokeWidth = 2
  ctx:beginPath()
  ctx.fillStyle = loaded.im
  ctx:fill()
end

```

But nothing is displayed on screen, do you have any idea ?

**Comment by starwing** [comment]
maybe you should do some draw operations between `beginPath` and `fill` ?

**Comment by iongion** [comment]
The `examples/images.lua` now contains Image usage sample
